name: 'RMD Render Action'
description: 'GitHub Action to render R Markdown documents using rocker/r-rmd'

inputs:
  input_file:
    description: 'Path to the input R Markdown file'
    required: true

outputs:
  output_files:
    description: 'Comma-separated list of rendered output files'

runs:
  using: 'docker'
  image: 'rocker/r-rmd'
  entrypoint: 'Rscript'
  args:
    - render.R
    - ${{ inputs.input_file }} 