name: 'RMD Render Action'
description: 'GitHub Action to render R Markdown documents using rocker/r-rmd'
branding:
  icon: 'book-open'
  color: 'blue'

inputs:
  input_file:
    description: 'Path to the input R Markdown file'
    required: true

outputs:
  output_files:
    description: 'Comma-separated list of rendered output files'

runs:
  using: 'docker'
  image: 'rocker/r-rmd'
  entrypoint: 'Rscript'
  args:
    - '-e'
    - |
      # Install required packages
      if (!requireNamespace("flexdashboard", quietly = TRUE)) {
        install.packages("flexdashboard")
      }
      
      # Render the document using YAML configuration
      rmarkdown::render(input = "${{ inputs.input_file }}")
      
      # List all generated files
      base_dir <- dirname("${{ inputs.input_file }}")
      base_name <- tools::file_path_sans_ext(basename("${{ inputs.input_file }}"))
      output_files <- list.files(
        path = base_dir,
        pattern = paste0("^", base_name, "\\.(pdf|html|docx)$"),
        full.names = TRUE
      )
      
      # Write output files to GitHub Actions environment
      writeLines(sprintf("::set-output name=output_files::%s", paste(output_files, collapse = ","))) 