name: 'R Markdown Render Action'
description: 'Renders R Markdown documents in multiple formats'

inputs:
  input_file:
    description: 'Path to the R Markdown file to render'
    required: true

outputs:
  output_files:
    description: 'Comma-separated list of generated output files'

runs:
  using: 'docker'
  image: 'slren/tidyverse-rmd'
  entrypoint: 'Rscript'
  args:
    - 'render.R'
    - ${{ inputs.input_file }} 