name: Test R Markdown Formats
on: [push]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Render Documents
        id: render_docs
        uses: ./
        with:
          input_file: 'test/test_formats.Rmd'
      
      - name: Upload Documents
        uses: actions/upload-artifact@v4
        with:
          name: rendered-documents
          path: ${{ steps.render_docs.outputs.output_files }}
      
      - name: Render Dashboard
        id: render_dash
        uses: ./
        with:
          input_file: 'test/test_dashboard.Rmd'
      
      - name: Upload Dashboard
        uses: actions/upload-artifact@v4
        with:
          name: rendered-dashboard
          path: ${{ steps.render_dash.outputs.output_files }} 