name: Test R Markdown Formats
on: [push]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # 预拉取基础镜像
      - name: Pull base image
        run: docker pull slren/tidyverse-rmd
      
      - name: Render Documents
        id: render_docs
        uses: ./
        with:
          input_file: 'test/test_formats.Rmd'
      
      # 列出生成的文件
      - name: List output files
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Test directory contents:"
          ls -la test/
      
      - name: Upload Documents
        uses: actions/upload-artifact@v4
        with:
          name: rendered-documents
          path: _output/
      
      - name: Render Dashboard
        id: render_dash
        uses: ./
        with:
          input_file: 'test/test_dashboard.Rmd'
      
      - name: Upload Dashboard
        uses: actions/upload-artifact@v4
        with:
          name: rendered-dashboard
          path: _output/ 