name: Test R Markdown Formats
on: [push]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # 配置 Docker 缓存
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      # 预拉取基础镜像
      - name: Pull base image
        run: docker pull rocker/r-rmd:latest
      
      # 缓存 R 包
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: .cache/R
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-
      
      - name: Render Documents
        id: render_docs
        uses: ./
        with:
          input_file: 'test/test_formats.Rmd'
      
      - name: Upload Documents
        uses: actions/upload-artifact@v4
        with:
          name: rendered-documents
          path: ${{ steps.render_docs.outputs.output_files }}
      
      - name: Render Dashboard
        id: render_dash
        uses: ./
        with:
          input_file: 'test/test_dashboard.Rmd'
      
      - name: Upload Dashboard
        uses: actions/upload-artifact@v4
        with:
          name: rendered-dashboard
          path: ${{ steps.render_dash.outputs.output_files }} 