name: Test R Markdown Formats
on: 
  push:
  workflow_dispatch:
    inputs:
      input_file:
        description: 'Path to the R Markdown file to render'
        required: true
        default: 'test/test_formats.Rmd'
        type: string

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing commits
    steps:
      # Checkout the repository code with proper authentication
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Pre-pull the Docker image to speed up the workflow
      # This step is optional but recommended for faster execution
      - name: Pull base image
        run: docker pull slren/tidyverse-rmd
      
      # Render the first R Markdown document (test_formats.Rmd)
      # This will generate PDF, HTML, and Word documents
      - name: Render Documents
        id: render_docs
        uses: ./
        with:
          input_file: ${{ github.event.inputs.input_file || 'test/test_formats.Rmd' }}

      ## do your own thing here if you want with the rendered files(under _output directory)
      
      ## Some examples:
      # Optional: Print output files for debugging
      - name: Print first render output
        run: |
          echo "Output files from first render:"
          echo "${{ steps.render_docs.outputs.output_files }}"
      
      # Optional: List files for debugging
      - name: List output files
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Test directory contents:"
          ls -la test/
      
      # Optional: Render second document
      - name: Render Dashboard
        id: render_dash
        uses: ./
        with:
          input_file: 'test/test_dashboard.Rmd'
      
      # Optional: Print output files for debugging
      - name: Print second render output
        run: |
          echo "Output files from second render:"
          echo "${{ steps.render_dash.outputs.output_files }}"
      
      # Optional: Configure Git for committing files
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      # Optional: Commit and push rendered files to repository
      - name: Commit and push rendered files
        run: |
          git add _output/
          git commit -m "Update rendered documents [skip ci]"
          git push origin HEAD:${{ github.ref }}
      
      # Optional: Upload rendered files as artifacts
      - name: Upload Rendered Documents
        uses: actions/upload-artifact@v4
        with:
          name: rendered-documents
          path: _output/ 